### ISSUE TITLE
Cross-tool config file

### ISSUE THREAD

**Issue by imikushin** [LK4D4/vndr#1]
Hey there,

[Trash](https://github.com/rancher/trash) author here :) 

How about we agree on common config filename ("vndr.cfg" and "trash.conf" could stay as fallback), changing it to "`vendor.conf`", for example. 

Then people could easily switch back and forth between `vndr` and `trash` tools.

**Comment by LK4D4** [comment]
@imikushin sure, vendor.conf sounds good to me.

**Comment by imikushin** [comment]
Cool, I'm updating trash then.
