### ISSUE TITLE
vndr sometimes fails when cloning large repos

### ISSUE THREAD

**Issue by pdalpra** [LK4D4/vndr#11]
Hi, 

I recently noticed that vndr may sometime fails when cloning large repos.
In my case, I'm depending on https://github.com/fsouza/go-dockerclient, which in turn depends on Docker's code itself, for which clones fails quite often with the following error: 

```
github.com/docker/docker: Err: exit status 128, out: Cloning into '/home/pdalpra/Work/golang/src/github.com/mycompany/myproject/vendor/github.com/docker/docker'...
error: index-pack died of signal 25
fatal: index-pack failed
```

WDYT of doing shallow clones when vendoring deps from Git repos ? As this would clone only the very last commit (which IMHO is acceptable for vendored dependencies), this may solve this issue and possibly speed up the cloning of repositories.

**Comment by LK4D4** [comment]
@pdalpra I'd love to do shallow clones, but I don't believe that it works with commit sha-s, which is the most popular way to specify the version.
I think that problem might be with too excessive parallelism. I will work on this today and then we'll see if it helps.

**Comment by pdalpra** [comment]
Damn, you're absolutely right, Git visibly doesn't let you combine shallow clones and cloning of a specific commit :/
Still, this pops only from time to time, I didn't manage to reproduce since then, most probably Github was a bit overloaded at that time.

Anyway, thank you for your work on vndr, best vendoring tool of all those I tried :+1:

**Comment by LK4D4** [comment]
@pdalpra Thanks for your kind words. I really appreciate it.
I'm going to close issue since it's hard to reproduce and probably a problem on a remote side. Feel free to open a new issue if you'll encounter the problem again.
I've opened #12 which in theory might make the experience on heavy loaded machines better.
Thanks!
