### ISSUE TITLE
vndr init doesn't get some of the dependencies 

### ISSUE THREAD

**Issue by DmitriyMV** [LK4D4/vndr#30]
For example - it will get the `github.com/mattn/go-colorable` and `github.com/mattn/go-isatty` for `github.com/fatih/color`, but will not get the transitive dependency of `golang.org/x/sys/unix` from https://github.com/mattn/go-isatty/blob/master/isatty_solaris.go#L7

**Comment by LK4D4** [comment]
@DmitriyMV is this with `vndr init`? Just `vndr` isn't supposed to download anything, not in `vendor.conf` because otherwise, you could end with some weird `appengine` code.

**Comment by DmitriyMV** [comment]
Yes - with `vndr init`

**Comment by LK4D4** [comment]
@DmitriyMV I suppose it might be windows problem :/ It works correctly for me.
Can you try again to confirm? Then I'll try to get windows box to test.

**Comment by DmitriyMV** [comment]
I tried it right now on my work Linux machine - still the same.

Code:
```
package main

import (
	"github.com/mattn/go-colorable"
)

func main() {
	colorable.NewColorableStdout()
}
```
go data:
```
dmitriy@MD-PC ~> go version
go version go1.8.1 linux/amd64

dmitriy@MD-PC ~> go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/dmitriy/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build870112013=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

Folder structure:
```
.
├── main.go
├── vendor
│   └── github.com
│       └── mattn
│           ├── go-colorable
│           │   ├── colorable_appengine.go
│           │   ├── colorable_others.go
│           │   ├── colorable_windows.go
│           │   ├── LICENSE
│           │   ├── noncolorable.go
│           │   └── README.md
│           └── go-isatty
│               ├── doc.go
│               ├── isatty_appengine.go
│               ├── isatty_bsd.go
│               ├── isatty_linux.go
│               ├── isatty_others.go
│               ├── isatty_solaris.go
│               ├── isatty_windows.go
│               ├── LICENSE
│               └── README.md
└── vendor.conf

5 directories, 17 files
```
No `golang.org/x/sys/unix` in my vendor =(

**Comment by LK4D4** [comment]
@DmitriyMV I don't understand. Did you do `vndr init` to get that `vendor.conf`? There can't be package in `vendor` if it isn't listed in `vendor.conf`.

**Comment by DmitriyMV** [comment]
Yes - I did `vndr init` to get this vendor.conf and vendor directory.

**Comment by LK4D4** [comment]
This happens when package is found in `$GOPATH`. I'll try to fix that this week.
