### ISSUE TITLE
vndr command doesn't work

### ISSUE THREAD

**Issue by chenminjian** [LK4D4/vndr#32]
I used /Users/chenminjian/dev/go_pack/bin/vndr command to download package in my work dir,but I didn't find any package in my vendor folder.
------my log-------
2017/03/23 13:17:33 Collecting initial packages
2017/03/23 13:17:33 Download dependencies
2017/03/23 13:17:33 	Clone github.com/spf13/pflag, revision 9ff6c6923cfffbcd502984b8e0c80539a94968b7
2017/03/23 13:17:33 	Clone https://github.com/dnephin/cobra.git to github.com/spf13/cobra, revision v1.5.1
2017/03/23 13:17:40 	Finished clone github.com/spf13/pflag
2017/03/23 13:17:44 	Finished clone github.com/spf13/cobra
2017/03/23 13:17:44 Dependencies downloaded. Download time: 11.000047077s
2017/03/23 13:17:44 Collecting all dependencies
2017/03/23 13:17:44 Clean vendor dir from unused packages
2017/03/23 13:17:44 Success
2017/03/23 13:17:44 Running time: 11.009391968s

**Comment by LK4D4** [comment]
@chenminjian can you please provide example project?
Please take a note that you must use the package in your code for vndr to keep it. Otherwise, it cleans everything unused.

**Comment by chenminjian** [comment]
I add “import github.com/dnephin/cobra”to my code, and then it success.Thanks.
