### ISSUE TITLE
Warn about unused packages listed in vendor.conf

### ISSUE THREAD

**Issue by ijc25** [LK4D4/vndr#33]
Typically the complete dependency tree needs to be flattened into `vendor.conf`, so if you vendor package `pkga` and it depends on `pkgb` you have both `pkga` and `pkgb` listed. If you then update to a newer version of `pkga` which no longer requires `pkgb` then you might not notice and remember to remove `pkgb` from `vendor.conf`.

It would be useful if `vndr` would warn when it noticed that it had garbage collected something explicitly listed in `vendor.conf` during `cleanVendor`.

It's also possible that I might remove the last usage of `pkga` in my code without noticing, this would highlight that too (but only if you happen to run `vndr`).

**Comment by LK4D4** [comment]
@ijc25 very good idea. Thanks. I will try to implement on the weekend.
