### ISSUE TITLE
Does not cleanup vendoring not referenced by `vendor.conf` if it is used

### ISSUE THREAD

**Issue by ijc** [LK4D4/vndr#63]
https://github.com/moby/buildkit/commit/e8dbd3aeb410a6b0fbf3d17eae9deed704ffd435 has a bug where the package `github.com/morikuni/aec` is not present in `vendor.conf` (it was accidentally dropped) but is used by the code and remains in `vendor/` after running `vndr`.

I would expect an error or at least a warning (which could be turned into an error with `-strict`, nb #62 might have an effect).

If I `rm -rf vendor && vndr` then the check done in `./hack/validate-vendor` does complain:
```
[...]
2018/03/08 14:39:04 	WARNING(verbose) github.com/morikuni/aec: cannot find package "github.com/morikuni/aec" in any of:
	/go/src/github.com/moby/buildkit/vendor/github.com/morikuni/aec (vendor tree)
	/go/src/github.com/moby/buildkit/vendor/github.com/morikuni/aec
	/usr/local/go/src/github.com/morikuni/aec (from $GOROOT)
	/go/src/github.com/morikuni/aec (from $GOPATH)
[...]
The result of vndr differs

 D vendor/github.com/morikuni/aec/LICENSE
 D vendor/github.com/morikuni/aec/README.md
 D vendor/github.com/morikuni/aec/aec.go
 D vendor/github.com/morikuni/aec/ansi.go
 D vendor/github.com/morikuni/aec/builder.go
 D vendor/github.com/morikuni/aec/sgr.go

Please vendor your package with github.com/LK4D4/vndr.
```

(without my `rm -rf vendor` the result can be seen [here](https://travis-ci.org/moby/buildkit/builds/350384696#L2259), which exhibits #62 as well)

**Comment by LK4D4** [comment]
@ijc thanks!
Would you mind to try the latest commit? I indeed all that time thought that vndr always removes `vendor` directory even though I removed those lines almost from the beginning :(

**Comment by ijc** [comment]
Confirmed, modifying https://github.com/moby/buildkit/commit/e8dbd3aeb410a6b0fbf3d17eae9deed704ffd435 to use `vndr` 15dc0965b7ba6dd78ae741e6fda33f23207033c4 meant that during `make validate-vendor` the `vndr` run (correctly) complains:
```
2018/03/27 16:26:19 	WARNING(verbose) github.com/morikuni/aec: cannot find package "github.com/morikuni/aec" in any of:
	/go/src/github.com/moby/buildkit/vendor/github.com/morikuni/aec (vendor tree)
	/go/src/github.com/moby/buildkit/vendor/github.com/morikuni/aec
	/usr/local/go/src/github.com/morikuni/aec (from $GOROOT)
	/go/src/github.com/morikuni/aec (from $GOPATH)
```
and then `validate-vendor` goes on to observe that `vendor/github.com/morikuni/aec/*` have been removed and errors out.

Thanks!
