### ISSUE TITLE
Infinite loop when an invalid version/tag is defined

### ISSUE THREAD

**Issue by fozcode** [LK4D4/vndr#78]
Feel free to close this with "don't define invalid tags" 😉 but...

Some of the packages I vendor have switched from using `X.Y.Z` format tags to `vX.Y.Z`, and I didn't notice this and bumped the version.  Running vndr was then giving me:

```
$ vndr github.com/labstack/gommon 0.2.8
2019/06/05 15:36:05 Collecting initial packages
2019/06/05 15:36:20 Download dependencies
2019/06/05 15:36:20 	Clone github.com/labstack/gommon, revision 0.2.8
2019/06/05 15:36:23 	Finished clone github.com/labstack/gommon
2019/06/05 15:36:24 	Clone github.com/labstack/gommon, revision 0.2.8
2019/06/05 15:36:26 	Finished clone github.com/labstack/gommon
2019/06/05 15:36:27 	Clone github.com/labstack/gommon, revision 0.2.8
2019/06/05 15:36:29 	Finished clone github.com/labstack/gommon
2019/06/05 15:36:30 	Clone github.com/labstack/gommon, revision 0.2.8
... and so on ...
```

It took me quite a while to figure out what was going on but of course changing `0.2.8` to `v0.2.8` fixed it.  It would be nice if vndr issued an error for bad tags instead of retrying forever.

**Comment by LK4D4** [comment]
@fozcode just to check :) Are you sure it doesn't die after 20 attempts?
Log messages are indeed confusing there, I'll fix it.

**Comment by LK4D4** [comment]
#79 should make it clear that clone fails way before 20th attempt.

**Comment by fozcode** [comment]
Ah yes you're right.  On the run that was confusing me I had this issue with multiple packages and after 6 minutes I just happened to kill it on the 20th attempt of the final package.  If I'd left it another few seconds I would have seen it error out.  So it's not infinite!  Thanks for the quick response :)
