### ISSUE TITLE
https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 410 Gone

### ISSUE THREAD

**Issue by siddanmk** [LK4D4/vndr#82]
When vndr command is run, I see this:
https://api.bitbucket.org/1.0/repositories/ww/goautoneg: 410 Gone
which is in https://github.com/LK4D4/vndr/blob/master/godl/vcs.go

Tried to open the page https://api.bitbucket.org/1.0/repositories/ww/goautoneg:
{"type": "error", "error": {"message": "Resource removed", "detail": "This API is no longer supported.\n\nFor information about its removal, please refer to the deprecation notice at: https://developer.atlassian.com/cloud/bitbucket/deprecation-notice-v1-apis/"}}

**Comment by LK4D4** [comment]
@siddanmk do you have `bitbucket` packages in your `vendor.conf` or is it just erroring out on any run?

**Comment by siddanmk** [comment]
I have bitbucket.org/ww/goautoneg 75cd24fc2f2c2a2088577d12123ddee5f54e0675 in vendor.conf

**Comment by LK4D4** [comment]
@siddanmk thanks for the report. Will be fixed in #83 and I will tag new version

**Comment by LK4D4** [comment]
@siddanmk https://github.com/LK4D4/vndr/releases/tag/v0.0.4

**Comment by siddanmk** [comment]
Thanks
