### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by cyphar** [LK4D4/vndr#9]
Hi @LK4D4. I'm currently packaging this for openSUSE, and it's a bit of a pain there's no version tags. Can you rectify that? Currently I'm doing something horrible with `0.0.0+r<num commits>` as the version number...

**Comment by LK4D4** [comment]
@cyphar sure, will do tomorrow!

**Comment by LK4D4** [comment]
@cyphar I made https://github.com/LK4D4/vndr/releases/tag/v0.0.1
Thanks!
